# Generated by Django 4.2.5 on 2023-10-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='created_at',
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='title',
            field=models.CharField(default='aiueo', max_length=255),
            preserve_default=False,
        ),
    ]
